/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ms_VMS */

#ifndef _Included_ms_VMS
#define _Included_ms_VMS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ms_VMS
 * Method:    setSymbol
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ms_VMS_setSymbol
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ms_VMS
 * Method:    getSymbol
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ms_VMS_getSymbol
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ms_VMS
 * Method:    processExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ms_VMS_processExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ms_VMS
 * Method:    diskTooLow
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_ms_VMS_diskTooLow
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ms_VMS
 * Method:    getFreeBlocks
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ms_VMS_getFreeBlocks
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ms_VMS
 * Method:    getTotalBlocks
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ms_VMS_getTotalBlocks
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ms_VMS
 * Method:    getDevices
 * Signature: (ILms/DeviceList;)V
 */
JNIEXPORT void JNICALL Java_ms_VMS_getDevices
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     ms_VMS
 * Method:    getDeviceInfo
 * Signature: (Lms/DeviceInfo;)V
 */
JNIEXPORT void JNICALL Java_ms_VMS_getDeviceInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ms_VMS
 * Method:    Requester
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ms_VMS_Requester
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ms_VMS
 * Method:    getPidAndCpu
 * Signature: (Lms/VMSProcessList;)V
 */
JNIEXPORT void JNICALL Java_ms_VMS_getPidAndCpu
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ms_VMS
 * Method:    getProcessName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ms_VMS_getProcessName
  (JNIEnv *, jclass, jint);

/*
 * Class:     ms_VMS
 * Method:    getCpuCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ms_VMS_getCpuCount
  (JNIEnv *, jclass);

/*
 * Class:     ms_VMS
 * Method:    getSysInfo
 * Signature: (Lms/SysInfo;)V
 */
JNIEXPORT void JNICALL Java_ms_VMS_getSysInfo
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
